version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    volumes:
      - ./server:/server
    env_file:
      - ./server/.env

  # server:
  #   build:
  #     context: ./server
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - NODE_ENV=production
  #   volumes:
  #     - ./server:/app
  #     - /app/node_modules 