version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./server:/server
      - server_python_cache:/root/.cache/pip
    env_file:
      - ./server/.env
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/server
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload --log-level debug

volumes:
  server_python_cache:

  # server:
  #   build:
  #     context: ./server
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - NODE_ENV=production
  #   volumes:
  #     - ./server:/app
  #     - /app/node_modules 