version: '3.8'

services:
  client:
    build:
      context: ./client
      target: dev  # Use the development stage from the Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - server

  server:
    build:
      context: ./server
    ports:
      - "8000:8000"
    environment:
      - CORS_ORIGINS=["http://localhost:3000"]
    volumes:
      - ./server:/server
      - /server/__pycache__
    env_file:
      - ./server/.env
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  # server:
  #   build:
  #     context: ./server
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - NODE_ENV=production
  #   volumes:
  #     - ./server:/app
  #     - /app/node_modules 