version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: dev  # Specify the development stage
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    volumes:
      - ./client:/app
      - client_node_modules:/app/node_modules
      - client_next_cache:/app/.next
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    volumes:
      - ./server:/server
    env_file:
      - ./server/.env

volumes:
  client_node_modules:
  client_next_cache:

  # server:
  #   build:
  #     context: ./server
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - NODE_ENV=production
  #   volumes:
  #     - ./server:/app
  #     - /app/node_modules 